In [2]:
pip install selenium

Requirement already satisfied: selenium in /home/pruebapython/Documentos/ciencia_de_datos/lib/python3.6/site-packages (3.141.0)
Requirement already satisfied: urllib3 in /home/pruebapython/Documentos/ciencia_de_datos/lib/python3.6/site-packages (from selenium) (1.25.8)
WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '/home/pruebapython/Documentos/ciencia_de_datos/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [63]:
from selenium import webdriver # importar al manejador
from selenium.webdriver.common.keys import Keys # clase que importa las teclas de caracteres especiales del teclado
from selenium.webdriver.common.by import By # nos servirá para buscar en el navegador por los elementos
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import pandas as pd

### Como extraer información con pandas

In [11]:
ff_options = webdriver.FirefoxOptions()
ff_options.add_argument("--disable-popup-blocking")

In [12]:

#creacion del constructor
driver = webdriver.Firefox(options = ff_options)

# parametros iniciales de la pantalla que se abrirá
driver.set_window_position(2000,0)
driver.maximize_window()
time.sleep(1)

# iniciamos las condiciones del navegador

driver.get("http://www.espn.com.mx/futbol/resultados")

# con assert, realmente confirmamos que crehana aparezca 
#en el titulo del navegador, es importante que recuerdes que se 
# reconoce diferencia entre mayusculas y minusculas
assert "espn" in driver.title


#driver.find_element_by_link_text("Iniciar sesión").click()
driver.find_element_by_link_text('Ligas').click()
driver.find_element_by_xpath('//*[@id="fittPageContainer"]/div[3]/div/div/div/div[2]/div[1]/div/div[1]/div/section/div/div/span[3]/a').click()

In [13]:
#nos interesa obtener la lista de goleradores de la liga MX

In [17]:
texto = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/div[4]/div[3]/div/div[1]/section/div/section/div/div[1]/section/div/div[2]/div/div[2]/table')

In [60]:
texto.text.split('\n')
jugadores = []
for cont,i in enumerate(texto.text.split('\n')):
    #print(cont, ' datos ', i)
    #print()
    if cont == 0:
        jugadores.append(i.split(' ')[1:])
    else:
        try :
            if i.split(' ')[0].isnumeric()==True:
                VAR_NOMBRE = i.split(' ')[1]
            else :
                VAR_NOMBRE = i.split(' ')[0]
            VAR_EQUIPO =i.split(' ')[-3]
            VAR_P = i.split(' ')[-2]
            VAR_G = i.split(' ')[-1]
            #['NOMBRE', 'EQUIPO', 'P', 'G']
            #print(VAR_NOMBRE, VAR_EQUIPO, VAR_P, VAR_G)
        except:
            
                VAR_NOMBRE = ''
                VAR_EQUIPO = ''
                VAR_P = 0
                VAR_G = 0
                #print(VAR_NOMBRE, VAR_EQUIPO, VAR_P, VAR_G)
        jugadores.append([VAR_NOMBRE, VAR_EQUIPO, VAR_P, VAR_G])

In [65]:
pd.DataFrame(jugadores[1:],columns = jugadores[0])

          NOMBRE       EQUIPO   P   G
0   André-Pierre         UANL  16  11
1        Nicolás      Pachuca  16   9
2        Rodrigo       Necaxa  14   9
3         Germán         Luis  17   7
4       Leonardo       Toluca  15   7
5         Víctor      Pachuca  17   6
6        Rogério         UNAM  17   6
7       Fernando       Puebla  17   6
8         Julián        Atlas  14   6
9         Harold       Santos  14   6
10         Ángel    Querétaro  17   5
11          Juan         UANL  17   5
12        Víctor         León  15   5
13         Diego      América  15   5
14        Alexis  Guadalajara  14   5
15        Milton       Necaxa  14   5
16         Julio        Atlas  13   5
17          Luis      Pachuca  17   4
18         Jesús  Guadalajara  17   4
19      Leonardo    Querétaro  16   4
20          Joel    Monterrey  15   4
21     Alejandro      América  15   4
22      Fernando       Juarez  14   4
23          Juan         Azul  14   4
24       Gonzalo           FC  14   4
25      Lisandro      Tijuana  13   4
26         Ángel         León  13   4
27   Maximiliano    Monterrey  17   3
28         Brian       Santos  17   3
29        Avilés      Pachuca  17   3
30        Camilo       Toluca  17   3
31       Eduardo       Santos  17   3
32   Maximiliano       Puebla  16   3
33       Roberto  Guadalajara  16   3
34       Roberto           FC  16   3
35       Florian         UANL  16   3
36          Jhon         Luis  16   3
37                              0   0
38                              0   0
39                              0   0
40         Henry      América  16   3
41         Brian           FC  16   3
42          José    Querétaro  15   3
43         Pablo       Puebla  15   3
44      Santiago         Azul  15   3
45        Carlos         UANL  15   3
46          Juan         UNAM  13   3
47       Joaquín      Tijuana  13   3
48        Miguel           FC  13   3
49        Carlos         Azul  12   3
50         Ángel  Guadalajara  12   3
51         Jorge         UNAM   9   3